[package]
name = "wol"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4", features = ["derive"] }
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
askama = "0.12"
askama_axum = "0.4"
