name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Rust toolchain (nightly) and wasm target
        run: rustup toolchain install nightly --allow-downgrade

      - name: Setup Rust toolchain and wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk

      - name: ⚡ Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build frontend
        run: cd frontend && trunk build --release

      - name: Run tests with tarpaulin
        env:
          RUSTFLAGS: -C debuginfo=2
        run: cargo tarpaulin --workspace --timeout 180 --out Xml
